kind: pipeline  
type: docker  
name: default  
  
steps:  
  - name: build  
    image: maven:3.8.1-jdk-11  
    commands:  
      - mvn clean install -B  
  
  - name: test  
    image: maven:3.8.1-jdk-11  
    commands:  
      - mvn test  
  
trigger:  
  branch:  
    - main  
    - master  
  event:  
    - push
