kind: pipeline
type: docker
name: default

steps:
  # 恢复缓存，减少依赖重新下载
  - name: restore-cache
    image: plugins/cache
    settings:
      restore: true
      mount:
        - target: /root/.m2/repository

  # 编译项目
  - name: build
    image: maven:3.8.1-jdk-8
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository -DskipTests=true"
    commands:
      - mvn clean package -DskipTests
      - ls -l target  # 列出 target 目录中的所有文件
      

  # 安装 curl 工具
  - name: install-curl
    image: alpine:latest
    commands:
      - apk add --no-cache curl
      
  # 启动 Docker Compose 服务
  - name: start-services
    image: docker:20.10
    commands:
      - curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - docker-compose --version  # 验证 Docker Compose 安装成功
      - docker-compose up -d  # 启动服务
      - sleep 60  # 等待服务启动
      - docker exec -i mysql-db mysql -uuser -ppassword newbee_mall_db < src/main/resources/newbee_mall_schema.sql  # 导入数据库文件

 # 启动 NewBee-Mall 服务
  - name: start-server
    image: openjdk:8-jre
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
    commands:
      - ls -l target  # 列出 target 目录中的所有文件，以验证 JAR 文件的路径
      - java -jar target/newbee-mall-1.0.0-SNAPSHOT.jar &
      - sleep 20  # 等待服务器启动

  # 健康检查
  - name: health-check
    image: curlimages/curl
    commands:
      - until curl -s http://localhost:8080; do sleep 5; echo "Waiting for NewBee-Mall server..."; done
      - echo "NewBee-Mall server is up!"

  # 运行 nuclei 漏洞扫描
  - name: nuclei-scan
    image: projectdiscovery/nuclei:latest
    commands:
      - nuclei -u http://localhost:8080  # 扫描 NewBee-Mall 服务

  # 重新缓存构建后的依赖
  - name: rebuild-cache
    image: plugins/cache
    settings:
      rebuild: true
      mount:
        - target: /root/.m2/repository

trigger:
  branch:
    - main
    - master
  event:
    - push
