kind: pipeline
type: docker
name: default

steps:
  # 恢复缓存，减少依赖重新下载
  - name: restore-cache
    image: plugins/cache
    settings:
      restore: true
      mount:
        - target: /root/.m2/repository

  # 编译项目
  - name: build
    image: maven:3.8.1-jdk-8
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository -DskipTests=true"
    commands:
      - mvn clean package -DskipTests
      - ls -l target  # 列出 target 目录中的所有文件

  # 启动 Docker Compose 服务
  - name: start-services
    image: docker:20.10
    commands:
      - apk add --no-cache docker-compose  # 安装 Docker Compose
      - docker-compose up -d  # 启动服务
      - sleep 20  # 等待服务启动
      - docker exec -i mysql-db mysql -uuser -ppassword newbee_mall_db < src/main/resources/newbee_mall_schema.sql  # 导入数据库文件

  # 健康检查
  - name: health-check
    image: curlimages/curl
    commands:
      - until curl -s http://localhost:8080; do sleep 5; echo "Waiting for NewBee-Mall server..."; done
      - echo "NewBee-Mall server is up!"

  # 运行 nuclei 漏洞扫描
  - name: nuclei-scan
    image: projectdiscovery/nuclei:latest
    commands:
      - nuclei -u http://localhost:8080  # 扫描 NewBee-Mall 服务

  # 重新缓存构建后的依赖
  - name: rebuild-cache
    image: plugins/cache
    settings:
      rebuild: true
      mount:
        - target: /root/.m2/repository

trigger:
  branch:
    - main
    - master
  event:
    - push
