version: '3.7'
services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: newbee_mall_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
